language: ruby
rvm:
- 2.3.0
notification:
  email: false
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  api_key:
    secure: OHWY7zg5yxouFStKpOqNR6bYX24cNA6PeD8h8QFIS05kgK+TZ/lAFOAuAaEQryhIazJYKe12N+k5OvZbCYK7IyaHzE/ahmr3uY6Gr6z1fu4RXYgQhHh3Tp7RjqQkn6w2z+HrEVAxtRLsqXPdVHzugU8WnhAJ0sXb0DXbMod70ksp+4RB7eM2cf5dM0pGhqKpYwtdBKWHlo7FtVrI/w/6NlNf+9Sff8noE8njQJIxmow5KcmA+HwAAVprA+DVzF9Lamk2yYY8Z47mTqHC1Ar23uTU6rwE6uOxlonRNgwPWX0Fi0os7f8SkU0u6FAaCeYOpvGPoscFI2nxI9LNHrR0VP+5an2oSWjkoMIIn+VbMxzEN+ck/HZ5z0DRbLfcTh+uA8z4gX1+mcY1W4+KSRolUzyhamDggTWnjq7bwdMEBuomOCkRaYXUQW4j2iExNo+dGAh0j85FGZz4XSpPJA5FSeCuRGHRdA0OOfJjEIS+TsEn5KfjXuBkddPshaumwooBFN0CVtT071RUtmGa71hm/ZTiWD2CEWTH31p3p/swQ6+mjGGOXmyRq4El4lImCDwBSavbEdehYmiWbctQjconFRcFntr659BIt4ooSu/NGsiOQU3tR2BWjxcgIyKHIr+4/fSEwBUslvCsqG866/+2fjF7tOYQRPRhSlNb7y71zQ0=
