language: ruby
rvm:
- 2.3.0
notification:
  email: false
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  api_key:
    secure: HlyTtltQK1EJALMKAlbgNUQVf7zZh2nQdglyTYA4mIZyId+7GlFcampjx9W81esrAj0pYC7418lciSz4oG5Br3FaOPMrPp3T2ZDTSGE9C4t1N60YnFIWUzerQ0KTno7wWL39X6bE7YbIE4GWPz8zpyyujYhAPE19ZatHrQP7ItPqyoIyl2cN15X3keIKyOS7Fu63CUG3BR72sacwN8HC169Fick4U7H6ihlJ00P5ulJ35LPbECsZf+DOwJKHbRp5LbDbFQAzMXgyvKrwMLp+yn3GD7dJRzm3/gjCTdhHUIvXiCsJEgkIwC8H42ls3hf26b+dpQbD1Hj1ncwJ7ApnuyEQzgRoIWdQNy6+BkfS+6aqNJrOqYLs+Pfe5kmUKlN4zxbaNMJLznFcmzcz1qCioQaE7W1PywCEA8NZpTI5pMb9DU5dkZ2/4giZVZnQsztZv6f7qP2N6o3eX5HR0EzBtvpQyzb2M58mHtQMXDzNZ2pCp+IUusCr5UhJWCCBUNOzGi47rW2htkii9Quv7B9XVfttIJGWtMVgrQGmNNbcCMgR0DRSUjCDVu4bbQ00A/dG/dDqixLoQ4YFvEzZ3KYlS6Yvq2ovNrnt4b2MoSzQBpAMXtKrHM0ggJe2Uw76OtXTPioafidABRSrW2SMeW7NZS+KfGE4NvFqIfrkBmBW1ts=
 app: tommserler
  on:
    repo: gunbladesohu/SDM2016TOMM