language: ruby
rvm:
- 2.3.0
notification:
  email: false
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  api_key:
    secure: LcfbbMGIyMfv9U8QGLWisteEn9Vaqq66ttUB0VWQVLIZVA+0aXD+3jlj2zPz4frINhZt4RmdfT81koSfYP7B+/gVIAjfGC4BgCci5ps2nFWEROIJKRVnR07/GJg2V+M3030LZacQM7Qz26urRBonzSH8BS5ZvaOUBIkRAKCFjric1m2lsyS4CCN96AYrwRBtJhCEI2MgNhIgCuqyDr0ho9irAsSx1cUFgND0SCLQOykgVBR6uNS5q7/hcNZQOsbbIVep4d44yygiZhhwm6oVgZf29hlsMnKKGWwyxCr3iSF/RTBiwtfhcxfLGKF1/utKMn6banYnseN1jg8KKZ/Dj47zF7OhDPTcngIGjbtvaGX21/XHOLlVmTX7IibFJleLwaA/j4PwZazY7BZsHLpANgmOfRXkBzsok1o3tHcR4MEaKbekDDCAzNh1WDT1Mf5Hnpx4QCOLyMbYjlHsqyXjkZ1mkLO8R6LYrk3vnMmVWcL7T8m9QSt8gL694slUHUzzYUdREoWC6e8LN7W+8eV8Zke2+WAohomk1KDLpVM9+vEMISbvo/LR/UfspbCKkD/i5Z8w3bw3AuTsVkGApamP0Mg1dLkRYvN4XVgpF/cYDoHQwA3XZmPtiqxKyj0/g92pun8JAiFKZpbHpGhDwLWR4ANjAxUkbBg2lE7B8gVPa58=
