language: ruby
rvm:
- 2.3.0
notification:
  email: false
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: FbAC4T73kYV/RJt8EQYYFpeNV5Wn0iRxqncl6sYHAAfvKSqlDTH19nDiF88zhvE5AnJ6Q8K7AhCeMuOEMgQ7aRZ/K+HbIPGuAEioQn3V/pgMfW3HAlXeJcQy/8XQqJnO9597stpRNttaDTOjBeyE36cHtYjaRJo7ZHPhd30PlFZ7eTdA4YHUuSMeubI4e3kG2sShpW/KUS0T0dSie1YzzCfDobFGYaXTlt7RHLBNUyAKe34A/yyYl/bUtYHYOucwslKORkGXtqIv1R4tjuJEcrN7Pr2JFK3ofeuWS+0e4VDFqw0l2Q0zBvQM4OsmOuTqXXadSqQpAtslsZlk/nRpHzoFsaxNxWvUOJpmruuRgV0IHOLrjsLsVFUGddw+eioVL8dzgxg/zAenuRMMTJ2ZGrnHbvHw385VKpT2UrTZpg2utUn1VeGFBf2BNbDA8rDhhrVwqtRhkbuaSv+H7PGYdVv865HmDHSzZ5ybYamDumGOazxWT9Zk47SHB/81Ags78J8NThnHqltAVkT+ej+n1c14qCBoOmiJBVvZhBcNGvtj1nCIIKfa2aAWWUnT8BvpPFS9Zss+hOpaiDKZnEG43daqCKOTca9QO39oOVbAvOw6dsREGupIlhp1WvZPak2c1Cat/pkpg3qwfcANSJ8Lte65IW5vWLtSESAypH+NjSQ=
  app: tommserler
  on:
    repo: gunbladesohu/SDM2016TOMM